# Use an official Python image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy all files
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r scripts/requirements.txt

# Expose the port Dash will run on
EXPOSE 8000

# Start the Dash app
CMD ["python", "scripts/app.py"]
