# Use full Python image that includes pip
FROM python:3.11

# Set working directory
WORKDIR /app

# Copy files
COPY . .

# Install Python dependencies
RUN pip install --no-cache-dir -r scripts/requirements.txt

# Expose the Dash port
EXPOSE 8000

# Run the Dash app
CMD ["python", "scripts/app.py"]
