district_to_state = {
    'Andaman Islands': 'Andaman & Nicobar Island',
    'Nicobars': 'Andaman & Nicobar Island',
    'Visakhapatnam': 'Andhra Pradesh',
    'Vizianagaram': 'Andhra Pradesh',
    'Warangal': 'Andhra Pradesh',
    'West Godavari': 'Andhra Pradesh',
    'Guntur': 'Andhra Pradesh',
    'Srikakulam': 'Andhra Pradesh',
    'Hyderabad': 'Andhra Pradesh',
    'Rangareddi': 'Andhra Pradesh',
    'Cuddapah': 'Andhra Pradesh',
    'Khammam': 'Andhra Pradesh',
    'Prakasam': 'Andhra Pradesh',
    'Medak': 'Andhra Pradesh',
    'Karimnagar': 'Andhra Pradesh',
    'East Godavari': 'Andhra Pradesh',
    'Nizamabad': 'Andhra Pradesh',
    'Nellore': 'Andhra Pradesh',
    'Nalgonda': 'Andhra Pradesh',
    'Anantapur': 'Andhra Pradesh',
    'Mahbubnagar': 'Andhra Pradesh',
    'Adilabad': 'Andhra Pradesh',
    'Chittoor': 'Andhra Pradesh',
    'Kurnool': 'Andhra Pradesh',
    'Krishna': 'Andhra Pradesh',
    'Papum Pare': 'Arunanchal Pradesh',
    'West Siang': 'Arunanchal Pradesh',
    'West Kameng': 'Arunanchal Pradesh',
    'Tirap': 'Arunanchal Pradesh',
    'Tawang': 'Arunanchal Pradesh',
    'Changlang': 'Arunanchal Pradesh',
    'Upper Siang': 'Arunanchal Pradesh',
    'Lower Subansiri': 'Arunanchal Pradesh',
    'Upper Subansiri': 'Arunanchal Pradesh',
    'Lohit': 'Arunanchal Pradesh',
    'East Kameng': 'Arunanchal Pradesh',
    'East Siang': 'Arunanchal Pradesh',
    'Dibang Valley': 'Arunanchal Pradesh',
    'Darrang': 'Assam',
    'Hailakandi': 'Assam',
    'North Cachar Hills': 'Assam',
    'Karbi Anglong': 'Assam',
    'Bongaigaon': 'Assam',
    'Karimganj': 'Assam',
    'Cachar': 'Assam',
    'Kamrup': 'Assam',
    'Nalbari': 'Assam',
    'Jorhat': 'Assam',
    'Dhubri': 'Assam',
    'Marigaon': 'Assam',
    'Nagaon': 'Assam',
    'Sibsagar': 'Assam',
    'Barpeta': 'Assam',
    'Kokrajhar': 'Assam',
    'Golaghat': 'Assam',
    'Tinsukia': 'Assam',
    'Goalpara': 'Assam',
    'Lakhimpur': 'Assam',
    'Dhemaji': 'Assam',
    'Sonitpur': 'Assam',
    'Dibrugarh': 'Assam',
    'Munger': 'Bihar',
    'Madhepura': 'Bihar',
    'Katihar': 'Bihar',
    'Lakhisarai': 'Bihar',
    'Rohtas': 'Bihar',
    'Araria': 'Bihar',
    'Madhubani': 'Bihar',
    'Nawada': 'Bihar',
    'Purba Champaran': 'Bihar',
    'Khagaria': 'Bihar',
    'Nalanda': 'Bihar',
    'Supaul': 'Bihar',
    'Purnia': 'Bihar',
    'Banka': 'Bihar',
    'Vaishali': 'Bihar',
    'Bhagalpur': 'Bihar',
    'Gopalganj': 'Bihar',
    'Darbhanga': 'Bihar',
    'Kaimur (Bhabua)': 'Bihar',
    'Saran': 'Bihar',
    'Aurangabad(Bihar)': 'Bihar',
    'Siwan': 'Bihar',
    'Jehanabad': 'Bihar',
    'Saharsa': 'Bihar',
    'Jamui': 'Bihar',
    'Sitamarhi': 'Bihar',
    'Sheohar': 'Bihar',
    'Begusarai': 'Bihar',
    'Sheikhpura': 'Bihar',
    'Pashchim Champaran': 'Bihar',
    'Samastipur': 'Bihar',
    'Muzaffarpur': 'Bihar',
    'Bhojpur': 'Bihar',
    'Patna': 'Bihar',
    'Gaya': 'Bihar',
    'Buxar': 'Bihar',
    'Kishanganj': 'Bihar',
    'Chandigarh': 'Chandigarh',
    'Dantewada': 'Chhattisgarh',
    'Jashpur': 'Chhattisgarh',
    'Koriya': 'Chhattisgarh',
    'Dhamtari': 'Chhattisgarh',
    'Kanker': 'Chhattisgarh',
    'Durg': 'Chhattisgarh',
    'Mahasamund': 'Chhattisgarh',
    'Kawardha': 'Chhattisgarh',
    'Korba': 'Chhattisgarh',
    'Janjgir - Champa': 'Chhattisgarh',
    'Bilaspur': 'Chhattisgarh',
    'Raigarh(Chhattisgarh)': 'Chhattisgarh',
    'Raipur': 'Chhattisgarh',
    'Rajnandgaon': 'Chhattisgarh',
    'Surguja': 'Chhattisgarh',
    'Bastar': 'Chhattisgarh',
    'Dadra & Nagar Haveli': 'Dadara & Nagar Havelli',
    'Diu': 'Daman & Diu',
    'Daman': 'Daman & Diu',
    'New Delhi': 'Delhi  & NCR',
    'North': 'Delhi  & NCR',
    'South West': 'Delhi  & NCR',
    'North West': 'Delhi  & NCR',
    'South': 'Delhi  & NCR',
    'East': 'Delhi  & NCR',
    'West': 'Delhi  & NCR',
    'North East': 'Delhi  & NCR',
    'Central': 'Delhi  & NCR',
    'North Goa': 'Goa',
    'South Goa': 'Goa',
    'Vadodara': 'Gujarat',
    'Surat': 'Gujarat',
    'Mahesana': 'Gujarat',
    'Junagadh': 'Gujarat',
    'Bharuch': 'Gujarat',
    'Narmada': 'Gujarat',
    'Kachchh': 'Gujarat',
    'Navsari': 'Gujarat',
    'Panch Mahals': 'Gujarat',
    'Patan': 'Gujarat',
    'Porbandar': 'Gujarat',
    'Rajkot': 'Gujarat',
    'Sabar Kantha': 'Gujarat',
    'Surendranagar': 'Gujarat',
    'Gandhinagar': 'Gujarat',
    'Jamnagar': 'Gujarat',
    'The Dangs': 'Gujarat',
    'Kheda': 'Gujarat',
    'Valsad': 'Gujarat',
    'Anand': 'Gujarat',
    'Bhavnagar': 'Gujarat',
    'Amreli': 'Gujarat',
    'Ahmadabad': 'Gujarat',
    'Dohad': 'Gujarat',
    'Banas Kantha': 'Gujarat',
    'Faridabad': 'Haryana',
    'Sonipat': 'Haryana',
    'Fatehabad': 'Haryana',
    'Sirsa': 'Haryana',
    'Rohtak': 'Haryana',
    'Yamunanagar': 'Haryana',
    'Ambala': 'Haryana',
    'Hisar': 'Haryana',
    'Jhajjar': 'Haryana',
    'Mahendragarh': 'Haryana',
    'Gurgaon': 'Haryana',
    'Panipat': 'Haryana',
    'Panchkula': 'Haryana',
    'Karnal': 'Haryana',
    'Bhiwani': 'Haryana',
    'Rewari': 'Haryana',
    'Jind': 'Haryana',
    'Kaithal': 'Haryana',
    'Kurukshetra': 'Haryana',
    'Kullu': 'Himachal Pradesh',
    'Lahul & Spiti': 'Himachal Pradesh',
    'Hamirpur(HP)': 'Himachal Pradesh',
    'Mandi': 'Himachal Pradesh',
    'Solan': 'Himachal Pradesh',
    'Kangra': 'Himachal Pradesh',
    'Chamba': 'Himachal Pradesh',
    'Shimla': 'Himachal Pradesh',
    'Sirmaur': 'Himachal Pradesh',
    'Kinnaur': 'Himachal Pradesh',
    'Una': 'Himachal Pradesh',
    'Bilaspur(HP)': 'Himachal Pradesh',
    'Kupwara': 'Jammu and Kashmir',
    'Punch': 'Jammu and Kashmir',
    'Jammu': 'Jammu and Kashmir',
    'Baramula': 'Jammu and Kashmir',
    'Srinagar': 'Jammu and Kashmir',
    'Pulwama': 'Jammu and Kashmir',
    'Doda': 'Jammu and Kashmir',
    'Leh (Ladakh)': 'Jammu and Kashmir',
    'Badgam': 'Jammu and Kashmir',
    'Rajauri': 'Jammu and Kashmir',
    'Kargil': 'Jammu and Kashmir',
    'Anantnag': 'Jammu and Kashmir',
    'Data Not Available': 'Jammu and Kashmir',
    'Kathua': 'Jammu and Kashmir',
    'Udhampur': 'Jammu and Kashmir',
    'Purba Singhbhum': 'Jharkhand',
    'Deoghar': 'Jharkhand',
    'Kodarma': 'Jharkhand',
    'Lohardaga': 'Jharkhand',
    'Hazaribagh': 'Jharkhand',
    'Chatra': 'Jharkhand',
    'Palamu': 'Jharkhand',
    'Pakaur': 'Jharkhand',
    'Pashchim Singhbhum': 'Jharkhand',
    'Dumka': 'Jharkhand',
    'Gumla': 'Jharkhand',
    'Garhwa': 'Jharkhand',
    'Sahibganj': 'Jharkhand',
    'Dhanbad': 'Jharkhand',
    'Bokaro': 'Jharkhand',
    'Giridih': 'Jharkhand',
    'Ranchi': 'Jharkhand',
    'Godda': 'Jharkhand',
    'Pakaur': 'Jharkhand',
    'Bellary': 'Karnataka',
    'Belgaum': 'Karnataka',
    'Gadag': 'Karnataka',
    'Bagalkot': 'Karnataka',
    'Tumkur': 'Karnataka',
    'Uttara Kannada': 'Karnataka',
    'Koppal': 'Karnataka',
    'Davanagere': 'Karnataka',
    'Mandya': 'Karnataka',
    'Bijapur': 'Karnataka',
    'Udupi': 'Karnataka',
    'Bidar': 'Karnataka',
    'Kolar': 'Karnataka',
    'Chitradurga': 'Karnataka',
    'Kodagu': 'Karnataka',
    'Bangalore': 'Karnataka',
    'Dakshina Kannada': 'Karnataka',
    'Chikmagalur': 'Karnataka',
    'Mysore': 'Karnataka',
    'Chamarajanagar': 'Karnataka',
    'Raichur': 'Karnataka',
    'Haveri': 'Karnataka',
    'Bangalore Rural': 'Karnataka',
    'Hassan': 'Karnataka',
    'Shimoga': 'Karnataka',
    'Gulbarga': 'Karnataka',
    'Dharwad': 'Karnataka',
    'Thiruvananthapuram': 'Kerala',
    'Ernakulam': 'Kerala',
    'Idukki': 'Kerala',
    'Pathanamthitta': 'Kerala',
    'Kannur': 'Kerala',
    'Malappuram': 'Kerala',
    'Kollam': 'Kerala',
    'Thrissur': 'Kerala',
    'Kottayam': 'Kerala',
    'Kozhikode': 'Kerala',
    'Alappuzha': 'Kerala',
    'Wayanad': 'Kerala',
    'Kasaragod': 'Kerala',
    'Palakkad': 'Kerala',
    'Lakshadweep': 'Lakshadweep',
    'Morena': 'Madhya Pradesh',
    'Hoshangabad': 'Madhya Pradesh',
    'Shajapur': 'Madhya Pradesh',
    'Gwalior': 'Madhya Pradesh',
    'Seoni': 'Madhya Pradesh',
    'Jhabua': 'Madhya Pradesh',
    'Sehore': 'Madhya Pradesh',
    'Satna': 'Madhya Pradesh',
    'Sheopur': 'Madhya Pradesh',
    'Dhar': 'Madhya Pradesh',
    'Bhopal': 'Madhya Pradesh',
    'Sidhi': 'Madhya Pradesh',
    'Chhindwara': 'Madhya Pradesh',
    'Betul': 'Madhya Pradesh',
    'West Nimar': 'Madhya Pradesh',
    'Rajgarh': 'Madhya Pradesh',
    'Chhatarpur': 'Madhya Pradesh',
    'Raisen': 'Madhya Pradesh',
    'Damoh': 'Madhya Pradesh',
    'Indore': 'Madhya Pradesh',
    'Narsimhapur': 'Madhya Pradesh',
    'Neemuch': 'Madhya Pradesh',
    'Balaghat': 'Madhya Pradesh',
    'Vidisha': 'Madhya Pradesh',
    'Bhind': 'Madhya Pradesh',
    'Ujjain': 'Madhya Pradesh',
    'Jabalpur': 'Madhya Pradesh',
    'Guna': 'Madhya Pradesh',
    'Shivpuri': 'Madhya Pradesh',
    'Dewas': 'Madhya Pradesh',
    'Panna': 'Madhya Pradesh',
    'Mandla': 'Madhya Pradesh',
    'Tikamgarh': 'Madhya Pradesh',
    'Umaria': 'Madhya Pradesh',
    'Dindori': 'Madhya Pradesh',
    'Katni': 'Madhya Pradesh',
    'East Nimar': 'Madhya Pradesh',
    'Ratlam': 'Madhya Pradesh',
    'Mandsaur': 'Madhya Pradesh',
    'Sagar': 'Madhya Pradesh',
    'Rewa': 'Madhya Pradesh',
    'Datia': 'Madhya Pradesh',
    'Barwani': 'Madhya Pradesh',
    'Harda': 'Madhya Pradesh',
    'Shahdol': 'Madhya Pradesh',
    'Washim': 'Maharashtra',
    'Bhandara': 'Maharashtra',
    'Jalgaon': 'Maharashtra',
    'Solapur': 'Maharashtra',
    'Nagpur': 'Maharashtra',
    'Chandrapur': 'Maharashtra',
    'Mumbai (Suburban)': 'Maharashtra',
    'Jalna': 'Maharashtra',
    'Wardha': 'Maharashtra',
    'Amravati': 'Maharashtra',
    'Gadchiroli': 'Maharashtra',
    'Nanded': 'Maharashtra',
    'Nandurbar': 'Maharashtra',
    'Sindhudurg': 'Maharashtra',
    'Thane': 'Maharashtra',
    'Nashik': 'Maharashtra',
    'Osmanabad': 'Maharashtra',
    'Gondiya': 'Maharashtra',
    'Mumbai': 'Maharashtra',
    'Pune': 'Maharashtra',
    'Buldana': 'Maharashtra',
    'Parbhani': 'Maharashtra',
    'Dhule': 'Maharashtra',
    'Satara': 'Maharashtra',
    'Bid': 'Maharashtra',
    'Hingoli': 'Maharashtra',
    'Akola': 'Maharashtra',
    'Ahmadnagar': 'Maharashtra',
    'Kolhapur': 'Maharashtra',
    'Ratnagiri': 'Maharashtra',
    'Yavatmal': 'Maharashtra',
    'Latur': 'Maharashtra',
    'Sangli': 'Maharashtra',
    'Aurangabad': 'Maharashtra',
    'Raigarh': 'Maharashtra',
    'Tamenglong': 'Manipur',
    'Thoubal': 'Manipur',
    'Churachandpur': 'Manipur',
    'Chandel': 'Manipur',
    'Senapati': 'Manipur',
    'Ukhrul': 'Manipur',
    'Bishnupur': 'Manipur',
    'Imphal West': 'Manipur',
    'Imphal East': 'Manipur',
    'West Garo Hills': 'Meghalaya',
    'West Khasi Hills': 'Meghalaya',
    'East Garo Hills': 'Meghalaya',
    'East Khasi Hills': 'Meghalaya',
    'South Garo Hills': 'Meghalaya',
    'Jaintia Hills': 'Meghalaya',
    'Ri Bhoi': 'Meghalaya',
    'Mamit': 'Mizoram',
    'Serchhip': 'Mizoram',
    'Aizawl': 'Mizoram',
    'Lunglei': 'Mizoram',
    'Kolasib': 'Mizoram',
    'Lawngtlai': 'Mizoram',
    'Champhai': 'Mizoram',
    'Saiha': 'Mizoram',
    'Phek': 'Nagaland',
    'Dimapur': 'Nagaland',
    'Kohima': 'Nagaland',
    'Mon': 'Nagaland',
    'Mokokchung': 'Nagaland',
    'Tuensang': 'Nagaland',
    'Wokha': 'Nagaland',
    'Zunheboto': 'Nagaland',
    'Sonepur': 'Orissa',
    'Balangir': 'Orissa',
    'Baleshwar': 'Orissa',
    'Bhadrak': 'Orissa',
    'Sambalpur': 'Orissa',
    'Rayagada': 'Orissa',
    'Kandhamal': 'Orissa',
    'Baudh': 'Orissa',
    'Khordha': 'Orissa',
    'Jajapur': 'Orissa',
    'Debagarh': 'Orissa',
    'Anugul': 'Orissa',
    'Kendujhar': 'Orissa',
    'Mayurbhanj': 'Orissa',
    'Puri': 'Orissa',
    'Kendrapara': 'Orissa',
    'Koraput': 'Orissa',
    'Cuttack': 'Orissa',
    'Jharsuguda': 'Orissa',
    'Kalahandi': 'Orissa',
    'Dhenkanal': 'Orissa',
    'Malkangiri': 'Orissa',
    'Nabarangapur': 'Orissa',
    'Ganjam': 'Orissa',
    'Gajapati': 'Orissa',
    'Nayagarh': 'Orissa',
    'Nuapada': 'Orissa',
    'Jagatsinghapur': 'Orissa',
    'Sundargarh': 'Orissa',
    'Bargarh': 'Orissa',
    'Yanam': 'Puducherry',
    'Mahe': 'Puducherry',
    'Pondicherry': 'Puducherry',
    'Karaikal': 'Puducherry',
    'Hoshiarpur': 'Punjab',
    'Faridkot': 'Punjab',
    'Ludhiana': 'Punjab',
    'Muktsar': 'Punjab',
    'Nawanshahr': 'Punjab',
    'Moga': 'Punjab',
    'Patiala': 'Punjab',
    'Kapurthala': 'Punjab',
    'Fatehgarh Sahib': 'Punjab',
    'Sangrur': 'Punjab',
    'Rupnagar': 'Punjab',
    'Mansa': 'Punjab',
    'Jalandhar': 'Punjab',
    'Gurdaspur': 'Punjab',
    'Firozpur': 'Punjab',
    'Bathinda': 'Punjab',
    'Amritsar': 'Punjab',
    'Hanumangarh': 'Rajasthan',
    'Baran': 'Rajasthan',
    'Sirohi': 'Rajasthan',
    'Dungarpur': 'Rajasthan',
    'Pali': 'Rajasthan',
    'Barmer': 'Rajasthan',
    'Ganganagar': 'Rajasthan',
    'Bikaner': 'Rajasthan',
    'Tonk': 'Rajasthan',
    'Jaipur': 'Rajasthan',
    'Dausa': 'Rajasthan',
    'Udaipur': 'Rajasthan',
    'Ajmer': 'Rajasthan',
    'Bundi': 'Rajasthan',
    'Sikar': 'Rajasthan',
    'Bharatpur': 'Rajasthan',
    'Rajsamand': 'Rajasthan',
    'Nagaur': 'Rajasthan',
    'Jalor': 'Rajasthan',
    'Karauli': 'Rajasthan',
    'Chittaurgarh': 'Rajasthan',
    'Kota': 'Rajasthan',
    'Jaisalmer': 'Rajasthan',
    'Sawai Madhopur': 'Rajasthan',
    'Bhilwara': 'Rajasthan',
    'Banswara': 'Rajasthan',
    'Churu': 'Rajasthan',
    'Jhalawar': 'Rajasthan',
    'Jhunjhunun': 'Rajasthan',
    'Jodhpur': 'Rajasthan',
    'Dhaulpur': 'Rajasthan',
    'Alwar': 'Rajasthan',
    'South District': 'Sikkim',
    'West District': 'Sikkim',
    'East District': 'Sikkim',
    'North District': 'Sikkim',
    'Theni': 'Tamil Nadu',
    'Virudhunagar': 'Tamil Nadu',
    'Viluppuram': 'Tamil Nadu',
    'Kanniyakumari': 'Tamil Nadu',
    'Erode': 'Tamil Nadu',
    'Dharmapuri': 'Tamil Nadu',
    'Thoothukkudi': 'Tamil Nadu',
    'Ramanathapuram': 'Tamil Nadu',
    'Cuddalore': 'Tamil Nadu',
    'Coimbatore': 'Tamil Nadu',
    'Perambalur': 'Tamil Nadu',
    'The Nilgiris': 'Tamil Nadu',
    'Dindigul': 'Tamil Nadu',
    'Madurai': 'Tamil Nadu',
    'Pudukkottai': 'Tamil Nadu',
    'Salem': 'Tamil Nadu',
    'Vellore': 'Tamil Nadu',
    'Ariyalur': 'Tamil Nadu',
    'Chennai': 'Tamil Nadu',
    'Thiruvarur': 'Tamil Nadu',
    'Thanjavur': 'Tamil Nadu',
    'Tiruchirappalli': 'Tamil Nadu',
    'Karur': 'Tamil Nadu',
    'Nagapattinam': 'Tamil Nadu',
    'Namakkal': 'Tamil Nadu',
    'Sivaganga': 'Tamil Nadu',
    'Tiruvannamalai': 'Tamil Nadu',
    'Thiruvallur': 'Tamil Nadu',
    'Kancheepuram': 'Tamil Nadu',
    'Tirunelveli': 'Tamil Nadu',
    'West Tripura': 'Tripura',
    'North Tripura': 'Tripura',
    'South Tripura': 'Tripura',
    'Dhalai': 'Tripura',
    'Mainpuri': 'Uttar Pradesh',
    'Faizabad': 'Uttar Pradesh',
    'Jaunpur': 'Uttar Pradesh',
    'Chitrakoot': 'Uttar Pradesh',
    'Mahrajganj': 'Uttar Pradesh',
    'Mahoba': 'Uttar Pradesh',
    'Aligarh': 'Uttar Pradesh',
    'Allahabad': 'Uttar Pradesh',
    'Etawah': 'Uttar Pradesh',
    'Ambedkar Nagar': 'Uttar Pradesh',
    'Kanpur Dehat': 'Uttar Pradesh',
    'Lalitpur': 'Uttar Pradesh',
    'Jalaun': 'Uttar Pradesh',
    'Jhansi': 'Uttar Pradesh',
    'Deoria': 'Uttar Pradesh',
    'Kaushambi': 'Uttar Pradesh',
    'Mirzapur': 'Uttar Pradesh',
    'Moradabad': 'Uttar Pradesh',
    'Auraiya': 'Uttar Pradesh',
    'Muzaffarnagar': 'Uttar Pradesh',
    'Kanpur Nagar': 'Uttar Pradesh',
    'Rae Bareli': 'Uttar Pradesh',
    'Azamgarh': 'Uttar Pradesh',
    'Budaun': 'Uttar Pradesh',
    'Ghaziabad': 'Uttar Pradesh',
    'Gautam Buddha Nagar': 'Uttar Pradesh',
    'Bulandshahr': 'Uttar Pradesh',
    'Etah': 'Uttar Pradesh',
    'Kannauj': 'Uttar Pradesh',
    'Agra': 'Uttar Pradesh',
    'Kushinagar': 'Uttar Pradesh',
    'Jyotiba Phule Nagar': 'Uttar Pradesh',
    'Lucknow': 'Uttar Pradesh',
    'Chandauli': 'Uttar Pradesh',
    'Mathura': 'Uttar Pradesh',
    'Shahjahanpur': 'Uttar Pradesh',
    'Hardoi': 'Uttar Pradesh',
    'Kheri': 'Uttar Pradesh',
    'Banda': 'Uttar Pradesh',
    'Gorakhpur': 'Uttar Pradesh',
    'Balrampur': 'Uttar Pradesh',
    'Sant Kabir Nagar': 'Uttar Pradesh',
    'Ballia': 'Uttar Pradesh',
    'Gonda': 'Uttar Pradesh',
    'Pilibhit': 'Uttar Pradesh',
    'Bahraich': 'Uttar Pradesh',
    'Pratapgarh': 'Uttar Pradesh',
    'Baghpat': 'Uttar Pradesh',
    'Siddharthnagar': 'Uttar Pradesh',
    'Mau': 'Uttar Pradesh',
    'Sant Ravidas Nagar Bhadohi': 'Uttar Pradesh',
    'Basti': 'Uttar Pradesh',
    'Hathras': 'Uttar Pradesh',
    'Unnao': 'Uttar Pradesh',
    'Bareilly': 'Uttar Pradesh',
    'Bijnor': 'Uttar Pradesh',
    'Meerut': 'Uttar Pradesh',
    'Sultanpur': 'Uttar Pradesh',
    'Farrukhabad': 'Uttar Pradesh',
    'Sitapur': 'Uttar Pradesh',
    'Rampur': 'Uttar Pradesh',
    'Fatehpur': 'Uttar Pradesh',
    'Shrawasti': 'Uttar Pradesh',
    'Barabanki': 'Uttar Pradesh',
    'Ghazipur': 'Uttar Pradesh',
    'Sonbhadra': 'Uttar Pradesh',
    'Firozabad': 'Uttar Pradesh',
    'Varanasi': 'Uttar Pradesh',
    'Saharanpur': 'Uttar Pradesh',
    'Hamirpur': 'Uttar Pradesh',
    'Hardwar': 'Uttarakhand',
    'Rudraprayag': 'Uttarakhand',
    'Bageshwar': 'Uttarakhand',
    'Pithoragarh': 'Uttarakhand',
    'Udham Singh Nagar': 'Uttarakhand',
    'Champawat': 'Uttarakhand',
    'Uttarkashi': 'Uttarakhand',
    'Almora': 'Uttarakhand',
    'Garhwal': 'Uttarakhand',
    'Chamoli': 'Uttarakhand',
    'Nainital': 'Uttarakhand',
    'Dehradun': 'Uttarakhand',
    'Tehri Garhwal': 'Uttarakhand',
    'Haora': 'West Bengal',
    'Birbhum': 'West Bengal',
    'Koch Bihar': 'West Bengal',
    'Uttar Dinajpur': 'West Bengal',
    'Puruliya': 'West Bengal',
    'Kolkata': 'West Bengal',
    'South  Twenty Four Parganas': 'West Bengal',
    'Hugli': 'West Bengal',
    'Medinipur': 'West Bengal',
    'Bankura': 'West Bengal',
    'Dakshin Dinajpur': 'West Bengal',
    'Barddhaman': 'West Bengal',
    'North Twenty Four Parganas': 'West Bengal',
    'Maldah': 'West Bengal',
    'Jalpaiguri': 'West Bengal',
    'Nadia': 'West Bengal',
    'Murshidabad': 'West Bengal',
    'Darjiling': 'West Bengal'
}




